title: "Avra Janz"
author: "Avra Janz"
description: "New York University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md"}
  # - {file: "README.md", title: "About"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:janzavra@nyu.edu"}
  # - {title: Scholar, icon: google-scholar, url: "https://scholar.google.com/citations?user=7o8LooUAAAAJ&hl=en&oi=ao"}
  # - {title: Github, icon: github, url: "https://github.com/janzavra"}
  
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
